# Generated by Django 5.1.2 on 2024-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=20)),
                ('student_dob', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=20)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('College_name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=30)),
                ('Current_year', models.CharField(max_length=10)),
                ('Year_of_graduation', models.CharField(max_length=5)),
                ('student_skills', models.CharField(max_length=50)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('Linkedin_link', models.CharField(max_length=100)),
                ('Github_link', models.CharField(max_length=100)),
                ('Resume_link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student_Registartion',
            },
        ),
        migrations.CreateModel(
            name='MentorRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentor_Name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=20)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('Expertise', models.CharField(max_length=30)),
                ('Job_title', models.CharField(max_length=30)),
                ('Company_organisation', models.CharField(max_length=50)),
                ('Year_of_experience', models.CharField(max_length=5)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('Focus_area', models.CharField(max_length=25)),
                ('Available_days', models.CharField(max_length=15)),
                ('Linkedin_link', models.CharField(max_length=100)),
                ('Github_link', models.CharField(max_length=100)),
                ('Pitch_deck_link', models.CharField(max_length=100)),
                ('Short_bio', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Mentor_Registartion',
            },
        ),
        migrations.CreateModel(
            name='StartupRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_Name', models.CharField(max_length=30)),
                ('founder_Name', models.CharField(max_length=50)),
                ('founded_date', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=20)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=30)),
                ('company_stage', models.CharField(max_length=30)),
                ('employee_count', models.CharField(max_length=10)),
                ('Funding_Received', models.CharField(max_length=30)),
                ('Key_technology', models.CharField(max_length=50)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('Focus_area', models.CharField(max_length=25)),
                ('Funding_duration', models.CharField(max_length=15)),
                ('Linkedin_link', models.CharField(max_length=100)),
                ('Github_link', models.CharField(max_length=100)),
                ('Pitch_deck_link', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Startup_Registartion',
            },
        ),
    ]
