# Generated by Django 5.1.2 on 2024-11-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorregistartion',
            old_name='Pitch_deck_link',
            new_name='resume_link',
        ),
    ]
