# Generated by Django 5.1.2 on 2024-11-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0002_rename_pitch_deck_link_mentorregistartion_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningregistartion',
            name='Current_year',
            field=models.CharField(max_length=25),
        ),
    ]
