# Generated by Django 5.1.2 on 2024-11-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0003_alter_elearningregistartion_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningregistartion',
            name='contact_email',
            field=models.CharField(max_length=50),
        ),
    ]
