# Generated by Django 5.1.2 on 2024-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0004_alter_elearningregistartion_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorregistartion',
            name='contact_email',
            field=models.CharField(max_length=100),
        ),
    ]
