# Generated by Django 5.1.2 on 2024-11-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0005_alter_mentorregistartion_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistartion',
            name='contact_email',
            field=models.CharField(max_length=50),
        ),
    ]
