# Generated by Django 5.1.2 on 2024-12-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0007_elearningregistartion_ep1_elearningregistartion_ep2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('student_Name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=20)),
                ('student_dob', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('College_name_Company_name', models.CharField(max_length=50)),
                ('Department_designation', models.CharField(max_length=30)),
                ('Current_year', models.CharField(blank=True, max_length=25, null=True)),
                ('Year_of_graduation', models.CharField(blank=True, max_length=5, null=True)),
                ('student_skills', models.CharField(max_length=50)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('domain', models.CharField(max_length=25)),
                ('duration', models.CharField(max_length=25)),
                ('Linkedin_link', models.CharField(max_length=100)),
                ('Github_link', models.CharField(max_length=100)),
                ('Resume_link', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('ep1', models.CharField(blank=True, max_length=300, null=True)),
                ('ep2', models.CharField(blank=True, max_length=300, null=True)),
                ('ep3', models.CharField(blank=True, max_length=300, null=True)),
                ('ep4', models.CharField(blank=True, max_length=300, null=True)),
                ('ep5', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'intern_Registartion',
            },
        ),
        migrations.RenameField(
            model_name='elearningregistartion',
            old_name='College_name',
            new_name='College_name_Company_name',
        ),
        migrations.RenameField(
            model_name='elearningregistartion',
            old_name='Department',
            new_name='Department_designation',
        ),
        migrations.AlterField(
            model_name='elearningregistartion',
            name='Current_year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='elearningregistartion',
            name='Year_of_graduation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
