# Generated by Django 5.1.2 on 2024-12-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0008_internregistartion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internregistartion',
            old_name='College_name_Company_name',
            new_name='College_name',
        ),
        migrations.RenameField(
            model_name='internregistartion',
            old_name='Department_designation',
            new_name='Department',
        ),
    ]
