# Generated by Django 5.1.4 on 2024-12-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0009_rename_college_name_company_name_internregistartion_college_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='userprofile/')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'User_profile',
            },
        ),
        migrations.CreateModel(
            name='Userauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_authenthication',
            },
        ),
    ]
