# Generated by Django 5.1.4 on 2024-12-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruisty', '0011_collegeregistartion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.CharField(max_length=85),
        ),
    ]
